"""C writer: provenance audit trail (full hash, command, patches, constants)."""

from regforge.ir import Device
from regforge.provenance import PatchRef, Provenance
from regforge.writers.c import CWriter


def _provenance():
    return Provenance(
        source_path="chip.svd",
        source_sha256="a" * 64,
        tool_version="9.9.9",
        command="regforge chip.svd",
        patches=[PatchRef(name="fix.yaml", sha256="b" * 64)],
    )


def test_full_hash_and_audit_lines_rendered():
    output = CWriter().render(Device(name="Chip", version="2.0"), _provenance())
    assert "Source:  chip.svd" in output
    assert "sha256:  " + "a" * 64 in output  # FULL 64-char hash in the banner
    assert 'CHIP_SVD_SHA256 "' + "a" * 64 + '"' in output  # full hash constant
    assert "Command: regforge chip.svd" in output
    assert "Patch:   fix.yaml (sha256: " + "b" * 16 + ")" in output
    assert "Generated by regforge 9.9.9 -- do not edit." in output


def test_no_provenance_omits_audit_trail():
    output = CWriter().render(Device(name="Chip", version="2.0"))
    assert "Source:" not in output
    assert "Command:" not in output
    assert "SVD_SHA256" not in output
    assert 'CHIP_SVD_VERSION "2.0"' in output  # identity constant still emitted
