/*
 * DemoMCU register definitions.
 * Minimal demo device used by the regforge test suite
 *
 * This file is generated by regforge. Do not edit.
 */
#ifndef DEMOMCU_H
#define DEMOMCU_H

#include <stdint.h>

/* GPIOA - General purpose I/O port A */
#define GPIOA_BASE (0x40020000UL)

/* GPIOA.MODER - Mode register */
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0x00000000UL))
#define GPIOA_MODER_MODE0_Pos (0U)
#define GPIOA_MODER_MODE0_Msk (0x00000003UL)
#define GPIOA_MODER_MODE0_INPUT (0U)
#define GPIOA_MODER_MODE0_OUTPUT (1U)
#define GPIOA_MODER_MODE0_ALTERNATE (2U)
#define GPIOA_MODER_MODE0_ANALOG (3U)

/* GPIOA.ODR - Output data register */
#define GPIOA_ODR (*(volatile uint32_t *)(GPIOA_BASE + 0x00000014UL))
#define GPIOA_ODR_OD0_Pos (0U)
#define GPIOA_ODR_OD0_Msk (0x00000001UL)

#endif /* DEMOMCU_H */
