/*
 * LintDemo register definitions.
 *
 * Device:  LintDemo (DemoCorp)
 *
 * Source:  lint_demo.svd
 * sha256:  61cac394cae331da8a7428e940bc06ff7f4bc205f059d841cf5e1fe898ba5d89
 * Command: regforge tests/fixtures/svd/lint_demo.svd -o tests/golden/c/lint_demo.h
 * Generated by regforge 0.0.1 -- do not edit.
 */
#ifndef REGFORGE_LINTDEMO_H
#define REGFORGE_LINTDEMO_H

#include <stdint.h>
#include <stddef.h>
#include <limits.h>

/* ========================================================================== */
/* Compiler compatibility */
/* ========================================================================== */
#ifndef REGFORGE_COMPAT_H
#define REGFORGE_COMPAT_H

/* Language standard as a comparable number (0 if not a Standard C compiler). */
#if defined(__STDC_VERSION__)
#  define REGFORGE_STDC __STDC_VERSION__
#else
#  define REGFORGE_STDC 0L
#endif

/* REGFORGE_STATIC_ASSERT(cond, tag, msg) -- compile-time check.
 * C++11+ and C11/C23 have a language construct; older dialects fall back to a
 * negative-array typedef named REGFORGE_ASSERT_<tag>. `tag` must be unique per
 * translation unit -- regforge passes a device-namespaced tag. */
#if defined(__cplusplus) && (__cplusplus >= 201103L)
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) static_assert(cond, msg)
#elif REGFORGE_STDC >= 201112L
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) _Static_assert(cond, msg)
#else
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) \
       typedef char REGFORGE_ASSERT_##tag[(cond) ? 1 : -1]
#endif

/* REGFORGE_INLINE -- inline with internal linkage.
 * `inline` is C99/C++; on C89 degrade to `static`, plus the unused attribute
 * (on compilers that support it) so an unreferenced helper stays warning-free. */
#if defined(__cplusplus) || REGFORGE_STDC >= 199901L
#  define REGFORGE_INLINE static inline
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_INLINE static __attribute__((unused))
#else
#  define REGFORGE_INLINE static
#endif

/* REGFORGE_MAYBE_UNUSED -- suppress "defined but not used" on an entity a given
 * translation unit may legitimately not reference. Used as a *prefix* on the
 * declaration (required by [[maybe_unused]]; also valid for __attribute__). */
#if defined(__cplusplus) && (__cplusplus >= 201703L)
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]
#elif REGFORGE_STDC >= 202311L
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]              /* C23 */
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_MAYBE_UNUSED __attribute__((unused))       /* GCC/Clang/armclang/armcc5/IAR8+ */
#else
#  define REGFORGE_MAYBE_UNUSED                                /* MSVC (no such warning) + exotic */
#endif

#endif /* REGFORGE_COMPAT_H */

/* ========================================================================== */
/* Device */
/* ========================================================================== */
#define LINTDEMO_ADDRESS_UNIT_BITS 8
REGFORGE_STATIC_ASSERT(CHAR_BIT == LINTDEMO_ADDRESS_UNIT_BITS, LINTDEMO_ADDRESS_UNIT_BITS_CHECK,
    "regforge: this header targets 8-bit address units; "
    "the compiler's CHAR_BIT disagrees -- regenerate with a matching emitter mode.");

#define LINTDEMO_BUS_WIDTH 32
#define LINTDEMO_SVD_SHA256 "61cac394cae331da8a7428e940bc06ff7f4bc205f059d841cf5e1fe898ba5d89"

/* ========================================================================== */
/* Interrupts */
/* ========================================================================== */
/* Device interrupt vector numbers (CMSIS IRQn_Type equivalent). Peripherals
 * link to these via their <NAME>_IRQ constants; the NVIC helpers take this
 * enum, so a raw int can't stand in for a vector number. */
typedef enum {
    LD_ADCA_IRQn     = 40,
    LD_TMRX0_IRQn    = 41,
    LD_TMRX1_IRQn    = 41,
    LD_TMRV_IRQn     = 42,
    LD_TMRU_IRQ_IRQn = 43
} ld_irqn_e;

/* ========================================================================== */
/* Peripherals */
/* ========================================================================== */

/* -------------------------------------------------------------------------- */
/* UART */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_UART_DR_OFFSET      (0x00000000UL)
#define LD_UART_RESERVED0_SIZE (0x000003FCUL)
#define LD_UART_SIZE           (0x00000400UL)

typedef struct {
    volatile uint32_t DR;                                 /* 0x00 */
    uint8_t           RESERVED0[LD_UART_RESERVED0_SIZE];  /* 0x04  (reserved) */
} ld_uart_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_uart_t, DR) == LD_UART_DR_OFFSET, LD_UART_DR_OFFSET_CHECK, "UART.DR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_uart_t) == LD_UART_SIZE, LD_UART_SIZE_CHECK, "UART struct size vs addressBlock");

/* UART @ 0x40004000 */
#define LD_UART_BASE (0x40004000UL)
REGFORGE_MAYBE_UNUSED static ld_uart_t *const LD_UART = (ld_uart_t *)LD_UART_BASE;

/* UART.DR */
#define LD_UART_DR (LD_UART->DR)


/* -------------------------------------------------------------------------- */
/* TIMER */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TIMER_CR_OFFSET      (0x00000000UL)
#define LD_TIMER_RESERVED0_SIZE (0x000000FCUL)
#define LD_TIMER_SIZE           (0x00000100UL)

typedef struct {
    volatile uint32_t CR;                                  /* 0x00 */
    uint8_t           RESERVED0[LD_TIMER_RESERVED0_SIZE];  /* 0x04  (reserved) */
} ld_timer_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_timer_t, CR) == LD_TIMER_CR_OFFSET, LD_TIMER_CR_OFFSET_CHECK, "TIMER.CR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_timer_t) == LD_TIMER_SIZE, LD_TIMER_SIZE_CHECK, "TIMER struct size vs addressBlock");

/* TIMER @ 0x40004200 */
#define LD_TIMER_BASE (0x40004200UL)
REGFORGE_MAYBE_UNUSED static ld_timer_t *const LD_TIMER = (ld_timer_t *)LD_TIMER_BASE;

/* TIMER.CR */
#define LD_TIMER_CR (LD_TIMER->CR)


/* -------------------------------------------------------------------------- */
/* FLASH */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_FLASH_CR_OFFSET      (0x00000000UL)
#define LD_FLASH_RESERVED0_SIZE (0x0000003CUL)
#define LD_FLASH_FAR_OFFSET     (0x00000040UL)
#define LD_FLASH_SIZE           (0x00000044UL)

typedef struct {
    volatile uint32_t CR;                                  /* 0x00 */
    uint8_t           RESERVED0[LD_FLASH_RESERVED0_SIZE];  /* 0x04  (reserved) */
    volatile uint32_t FAR;                                 /* 0x40 */
} ld_flash_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_flash_t, CR) == LD_FLASH_CR_OFFSET, LD_FLASH_CR_OFFSET_CHECK, "FLASH.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_flash_t, FAR) == LD_FLASH_FAR_OFFSET, LD_FLASH_FAR_OFFSET_CHECK, "FLASH.FAR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_flash_t) == LD_FLASH_SIZE, LD_FLASH_SIZE_CHECK, "FLASH struct size vs addressBlock");

/* FLASH @ 0x40010000 */
#define LD_FLASH_BASE (0x40010000UL)
REGFORGE_MAYBE_UNUSED static ld_flash_t *const LD_FLASH = (ld_flash_t *)LD_FLASH_BASE;

/* FLASH.CR */
#define LD_FLASH_CR (LD_FLASH->CR)

/* FLASH.FAR */
#define LD_FLASH_FAR (LD_FLASH->FAR)


/* -------------------------------------------------------------------------- */
/* DMA */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_DMA_CR_OFFSET      (0x00000000UL)
#define LD_DMA_RESERVED0_SIZE (0x0000000CUL)
#define LD_DMA_BUFFER0_OFFSET (0x00000010UL)
#define LD_DMA_BUFFER0_COUNT  (8U)
#define LD_DMA_SIZE           (0x00000030UL)

typedef struct {
    volatile uint32_t CR;                                /* 0x00 */
    uint8_t           RESERVED0[LD_DMA_RESERVED0_SIZE];  /* 0x04  (reserved) */
    volatile uint32_t BUFFER0[LD_DMA_BUFFER0_COUNT];     /* 0x10  (buffer) */
} ld_dma_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dma_t, CR) == LD_DMA_CR_OFFSET, LD_DMA_CR_OFFSET_CHECK, "DMA.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_dma_t, BUFFER0) == LD_DMA_BUFFER0_OFFSET, LD_DMA_BUFFER0_OFFSET_CHECK, "DMA.BUFFER0 offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_dma_t) == LD_DMA_SIZE, LD_DMA_SIZE_CHECK, "DMA struct size vs addressBlock");

/* DMA @ 0x40020000 */
#define LD_DMA_BASE (0x40020000UL)
REGFORGE_MAYBE_UNUSED static ld_dma_t *const LD_DMA = (ld_dma_t *)LD_DMA_BASE;

/* DMA.CR */
#define LD_DMA_CR (LD_DMA->CR)


/* -------------------------------------------------------------------------- */
/* FIFO */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_FIFO_CR_OFFSET      (0x00000000UL)
#define LD_FIFO_RESERVED0_SIZE (0x00001FFCUL)
#define LD_FIFO_DATA_OFFSET    (0x00002000UL)
#define LD_FIFO_SIZE           (0x00002004UL)

typedef struct {
    volatile uint32_t CR;                                 /* 0x00 */
    uint8_t           RESERVED0[LD_FIFO_RESERVED0_SIZE];  /* 0x04  (reserved) */
    volatile uint32_t DATA;                               /* 0x2000 */
} ld_fifo_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_fifo_t, CR) == LD_FIFO_CR_OFFSET, LD_FIFO_CR_OFFSET_CHECK, "FIFO.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifo_t, DATA) == LD_FIFO_DATA_OFFSET, LD_FIFO_DATA_OFFSET_CHECK, "FIFO.DATA offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_fifo_t) == LD_FIFO_SIZE, LD_FIFO_SIZE_CHECK, "FIFO struct size vs addressBlock");

/* FIFO @ 0x40040000 */
#define LD_FIFO_BASE (0x40040000UL)
REGFORGE_MAYBE_UNUSED static ld_fifo_t *const LD_FIFO = (ld_fifo_t *)LD_FIFO_BASE;

/* FIFO.CR */
#define LD_FIFO_CR (LD_FIFO->CR)

/* FIFO.DATA */
#define LD_FIFO_DATA (LD_FIFO->DATA)


/* -------------------------------------------------------------------------- */
/* MISC */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_MISC_REG_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t REG;  /* 0x00 */
} ld_misc_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_misc_t, REG) == LD_MISC_REG_OFFSET, LD_MISC_REG_OFFSET_CHECK, "MISC.REG offset");

/* MISC @ 0x40030000 */
#define LD_MISC_BASE (0x40030000UL)
REGFORGE_MAYBE_UNUSED static ld_misc_t *const LD_MISC = (ld_misc_t *)LD_MISC_BASE;

/* MISC.REG */
#define LD_MISC_REG (LD_MISC->REG)


/* -------------------------------------------------------------------------- */
/* FPU_CPACR */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_FPU_CPACR_CPACR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CPACR;  /* 0x00 */
} ld_fpu_cpacr_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_fpu_cpacr_t, CPACR) == LD_FPU_CPACR_CPACR_OFFSET, LD_FPU_CPACR_CPACR_OFFSET_CHECK, "FPU_CPACR.CPACR offset");

/* FPU_CPACR @ 0x40050000 */
#define LD_FPU_CPACR_BASE (0x40050000UL)
REGFORGE_MAYBE_UNUSED static ld_fpu_cpacr_t *const LD_FPU_CPACR = (ld_fpu_cpacr_t *)LD_FPU_CPACR_BASE;

/* FPU_CPACR.CPACR */
#define LD_FPU_CPACR_CPACR (LD_FPU_CPACR->CPACR)


/* -------------------------------------------------------------------------- */
/* FPU */
/* family FPU: split 2 ways by layout (FPU_CPACR | FPU); first differs at CPACR */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_FPU_FPCCR_OFFSET (0x00000000UL)
#define LD_FPU_FPCAR_OFFSET (0x00000004UL)

typedef struct {
    volatile uint32_t FPCCR;  /* 0x00 */
    volatile uint32_t FPCAR;  /* 0x04 */
} ld_fpu_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_fpu_t, FPCCR) == LD_FPU_FPCCR_OFFSET, LD_FPU_FPCCR_OFFSET_CHECK, "FPU.FPCCR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fpu_t, FPCAR) == LD_FPU_FPCAR_OFFSET, LD_FPU_FPCAR_OFFSET_CHECK, "FPU.FPCAR offset");

/* FPU @ 0x40051000 */
#define LD_FPU_BASE (0x40051000UL)
REGFORGE_MAYBE_UNUSED static ld_fpu_t *const LD_FPU = (ld_fpu_t *)LD_FPU_BASE;

/* FPU.FPCCR */
#define LD_FPU_FPCCR (LD_FPU->FPCCR)

/* FPU.FPCAR */
#define LD_FPU_FPCAR (LD_FPU->FPCAR)


/* -------------------------------------------------------------------------- */
/* TMR */
/* family TMR: split 2 ways by layout (TMR0 | TIMER_ADV); first differs at RCR */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TMR_CR1_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR1;  /* 0x00 */
} ld_tmr_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmr_t, CR1) == LD_TMR_CR1_OFFSET, LD_TMR_CR1_OFFSET_CHECK, "TMR.CR1 offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_tmr_t * accepts any of them. */
typedef ld_tmr_t ld_tmr0_t;

/* TMR0 @ 0x40052000 */
#define LD_TMR0_BASE (0x40052000UL)
REGFORGE_MAYBE_UNUSED static ld_tmr_t *const LD_TMR0 = (ld_tmr_t *)LD_TMR0_BASE;

/* TMR0.CR1 */
#define LD_TMR0_CR1 (LD_TMR0->CR1)


/* -------------------------------------------------------------------------- */
/* TIMER_ADV */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TIMER_ADV_CR1_OFFSET (0x00000000UL)
#define LD_TIMER_ADV_RCR_OFFSET (0x00000004UL)

typedef struct {
    volatile uint32_t CR1;  /* 0x00 */
    volatile uint32_t RCR;  /* 0x04 */
} ld_timer_adv_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_timer_adv_t, CR1) == LD_TIMER_ADV_CR1_OFFSET, LD_TIMER_ADV_CR1_OFFSET_CHECK, "TIMER_ADV.CR1 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_timer_adv_t, RCR) == LD_TIMER_ADV_RCR_OFFSET, LD_TIMER_ADV_RCR_OFFSET_CHECK, "TIMER_ADV.RCR offset");

/* TIMER_ADV @ 0x40053000 */
#define LD_TIMER_ADV_BASE (0x40053000UL)
REGFORGE_MAYBE_UNUSED static ld_timer_adv_t *const LD_TIMER_ADV = (ld_timer_adv_t *)LD_TIMER_ADV_BASE;

/* TIMER_ADV.CR1 */
#define LD_TIMER_ADV_CR1 (LD_TIMER_ADV->CR1)

/* TIMER_ADV.RCR */
#define LD_TIMER_ADV_RCR (LD_TIMER_ADV->RCR)


/* -------------------------------------------------------------------------- */
/* ADCA (family: ADCA, ADCB) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_ADCA_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_adca_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_adca_t, CR) == LD_ADCA_CR_OFFSET, LD_ADCA_CR_OFFSET_CHECK, "ADCA.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_adca_t * accepts any of them. */
typedef ld_adca_t ld_adcb_t;

/* ADCA @ 0x40054000 */
#define LD_ADCA_BASE (0x40054000UL)
REGFORGE_MAYBE_UNUSED static ld_adca_t *const LD_ADCA = (ld_adca_t *)LD_ADCA_BASE;
#define LD_ADCA_IRQ LD_ADCA_IRQn  /* vector 40 */

/* ADCA.CR */
#define LD_ADCA_CR (LD_ADCA->CR)

/* ADCB @ 0x40055000 */
#define LD_ADCB_BASE (0x40055000UL)
REGFORGE_MAYBE_UNUSED static ld_adca_t *const LD_ADCB = (ld_adca_t *)LD_ADCB_BASE;

/* ADCB.CR */
#define LD_ADCB_CR (LD_ADCB->CR)


/* -------------------------------------------------------------------------- */
/* TMRX (family: TMRX0, TMRX1, TMRV) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TMRX_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_tmrx_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmrx_t, CR) == LD_TMRX_CR_OFFSET, LD_TMRX_CR_OFFSET_CHECK, "TMRX.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_tmrx_t * accepts any of them. */
typedef ld_tmrx_t ld_tmrx0_t;
typedef ld_tmrx_t ld_tmrx1_t;
typedef ld_tmrx_t ld_tmrv_t;

/* TMRX0 @ 0x40056000 */
#define LD_TMRX0_BASE (0x40056000UL)
REGFORGE_MAYBE_UNUSED static ld_tmrx_t *const LD_TMRX0 = (ld_tmrx_t *)LD_TMRX0_BASE;
#define LD_TMRX0_IRQ LD_TMRX0_IRQn  /* vector 41 -- shared with LD_TMRX1; demux in ISR */

/* TMRX0.CR */
#define LD_TMRX0_CR (LD_TMRX0->CR)

/* TMRX1 @ 0x40056100 */
#define LD_TMRX1_BASE (0x40056100UL)
REGFORGE_MAYBE_UNUSED static ld_tmrx_t *const LD_TMRX1 = (ld_tmrx_t *)LD_TMRX1_BASE;
#define LD_TMRX1_IRQ LD_TMRX1_IRQn  /* vector 41 -- shared with LD_TMRX0; demux in ISR */

/* TMRX1.CR */
#define LD_TMRX1_CR (LD_TMRX1->CR)

/* TMRV @ 0x40062000 */
#define LD_TMRV_BASE (0x40062000UL)
REGFORGE_MAYBE_UNUSED static ld_tmrx_t *const LD_TMRV = (ld_tmrx_t *)LD_TMRV_BASE;
#define LD_TMRV_IRQ LD_TMRV_IRQn  /* vector 42 */

/* TMRV.CR */
#define LD_TMRV_CR (LD_TMRV->CR)


/* -------------------------------------------------------------------------- */
/* DMAX */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_DMAX_CH_OFFSET         (0x00000000UL)
#define LD_DMAX_CH_STRIDE         (0x00000010UL)
#define LD_DMAX_CH_COUNT          (2U)
#define LD_DMAX_CH_CTRL_OFFSET    (0x00000000UL)
#define LD_DMAX_CH_RESERVED0_SIZE (0x0000000CUL)
#define LD_DMAX_EXTRA_OFFSET      (0x00000020UL)
#define LD_DMAX_EXTRA_SIZE        (0x00000004UL)
#define LD_DMAX_EXTRA_CTRL_OFFSET (0x00000000UL)

/* DMAX.CH (2 elements, 0x10 bytes apart) */
typedef struct {
    volatile uint32_t CTRL;                                  /* 0x00 */
    uint8_t           RESERVED0[LD_DMAX_CH_RESERVED0_SIZE];  /* 0x04  (reserved) */
} ld_dmax_ch_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_ch_t, CTRL) == LD_DMAX_CH_CTRL_OFFSET, LD_DMAX_CH_CTRL_OFFSET_CHECK, "DMAX.CH.CTRL offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_dmax_ch_t) == LD_DMAX_CH_STRIDE, LD_DMAX_CH_SIZE_CHECK, "DMAX.CH element size vs dimIncrement");

/* DMAX.EXTRA */
typedef struct {
    volatile uint32_t CTRL;  /* 0x00 */
} ld_dmax_extra_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_extra_t, CTRL) == LD_DMAX_EXTRA_CTRL_OFFSET, LD_DMAX_EXTRA_CTRL_OFFSET_CHECK, "DMAX.EXTRA.CTRL offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_dmax_extra_t) == LD_DMAX_EXTRA_SIZE, LD_DMAX_EXTRA_SIZE_CHECK, "DMAX.EXTRA size vs its last register");

typedef struct {
    ld_dmax_ch_t    CH[LD_DMAX_CH_COUNT];  /* 0x00 */
    ld_dmax_extra_t EXTRA;                 /* 0x20 */
} ld_dmax_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_t, CH) == LD_DMAX_CH_OFFSET, LD_DMAX_CH_OFFSET_CHECK, "DMAX.CH offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_t, EXTRA) == LD_DMAX_EXTRA_OFFSET, LD_DMAX_EXTRA_OFFSET_CHECK, "DMAX.EXTRA offset");
REGFORGE_STATIC_ASSERT(sizeof(((ld_dmax_t *)0)->CH) == LD_DMAX_CH_COUNT * LD_DMAX_CH_STRIDE, LD_DMAX_CH_ARRAY_CHECK, "DMAX.CH array size");
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_t, CH) + (LD_DMAX_CH_COUNT - 1U) * sizeof(((ld_dmax_t *)0)->CH[0]) == LD_DMAX_CH_OFFSET + (LD_DMAX_CH_COUNT - 1U) * LD_DMAX_CH_STRIDE, LD_DMAX_CH_LAST_CHECK, "DMAX.CH[1] offset via the struct");

/* DMAX @ 0x40057000 */
#define LD_DMAX_BASE (0x40057000UL)
REGFORGE_MAYBE_UNUSED static ld_dmax_t *const LD_DMAX = (ld_dmax_t *)LD_DMAX_BASE;

/* DMAX.CH[2].CTRL */
#define LD_DMAX_CH_CTRL(ch_index) (LD_DMAX->CH[(ch_index)].CTRL)

/* DMAX.EXTRA.CTRL */
#define LD_DMAX_EXTRA_CTRL (LD_DMAX->EXTRA.CTRL)


/* -------------------------------------------------------------------------- */
/* TMRY (family: TMRY0, TMRY1) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TMRY_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_tmry_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmry_t, CR) == LD_TMRY_CR_OFFSET, LD_TMRY_CR_OFFSET_CHECK, "TMRY.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_tmry_t * accepts any of them. */
typedef ld_tmry_t ld_tmry0_t;
typedef ld_tmry_t ld_tmry1_t;

/* TMRY0 @ 0x40058000 */
#define LD_TMRY0_BASE (0x40058000UL)
REGFORGE_MAYBE_UNUSED static ld_tmry_t *const LD_TMRY0 = (ld_tmry_t *)LD_TMRY0_BASE;

/* TMRY0.CR */
#define LD_TMRY0_CR (LD_TMRY0->CR)

/* TMRY1 @ 0x40058100 */
#define LD_TMRY1_BASE (0x40058100UL)
REGFORGE_MAYBE_UNUSED static ld_tmry_t *const LD_TMRY1 = (ld_tmry_t *)LD_TMRY1_BASE;

/* TMRY1.CR */
#define LD_TMRY1_CR (LD_TMRY1->CR)


/* -------------------------------------------------------------------------- */
/* TMRZ (family: TMRZ0, TMRZ1, TMRZ2) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TMRZ_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_tmrz_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmrz_t, CR) == LD_TMRZ_CR_OFFSET, LD_TMRZ_CR_OFFSET_CHECK, "TMRZ.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_tmrz_t * accepts any of them. */
typedef ld_tmrz_t ld_tmrz0_t;
typedef ld_tmrz_t ld_tmrz1_t;
typedef ld_tmrz_t ld_tmrz2_t;

/* TMRZ0 @ 0x40059000 */
#define LD_TMRZ0_BASE (0x40059000UL)
REGFORGE_MAYBE_UNUSED static ld_tmrz_t *const LD_TMRZ0 = (ld_tmrz_t *)LD_TMRZ0_BASE;

/* TMRZ0.CR */
#define LD_TMRZ0_CR (LD_TMRZ0->CR)

/* TMRZ1 @ 0x40059100 */
#define LD_TMRZ1_BASE (0x40059100UL)
REGFORGE_MAYBE_UNUSED static ld_tmrz_t *const LD_TMRZ1 = (ld_tmrz_t *)LD_TMRZ1_BASE;

/* TMRZ1.CR */
#define LD_TMRZ1_CR (LD_TMRZ1->CR)

/* TMRZ2 @ 0x40059200 */
#define LD_TMRZ2_BASE (0x40059200UL)
REGFORGE_MAYBE_UNUSED static ld_tmrz_t *const LD_TMRZ2 = (ld_tmrz_t *)LD_TMRZ2_BASE;

/* TMRZ2.CR */
#define LD_TMRZ2_CR (LD_TMRZ2->CR)


/* -------------------------------------------------------------------------- */
/* TMRW */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TMRW_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_tmrw_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmrw_t, CR) == LD_TMRW_CR_OFFSET, LD_TMRW_CR_OFFSET_CHECK, "TMRW.CR offset");

/* TMRW @ 0x4005A000 */
#define LD_TMRW_BASE (0x4005A000UL)
REGFORGE_MAYBE_UNUSED static ld_tmrw_t *const LD_TMRW = (ld_tmrw_t *)LD_TMRW_BASE;

/* TMRW.CR */
#define LD_TMRW_CR (LD_TMRW->CR)


/* -------------------------------------------------------------------------- */
/* NOTDIM */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_NOTDIM_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_notdim_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_notdim_t, CR) == LD_NOTDIM_CR_OFFSET, LD_NOTDIM_CR_OFFSET_CHECK, "NOTDIM.CR offset");

/* NOTDIM @ 0x4005B000 */
#define LD_NOTDIM_BASE (0x4005B000UL)
REGFORGE_MAYBE_UNUSED static ld_notdim_t *const LD_NOTDIM = (ld_notdim_t *)LD_NOTDIM_BASE;

/* NOTDIM.CR */
#define LD_NOTDIM_CR (LD_NOTDIM->CR)


/* -------------------------------------------------------------------------- */
/* SAME (family: SAME0, SAME1) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_SAME_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_same_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_same_t, CR) == LD_SAME_CR_OFFSET, LD_SAME_CR_OFFSET_CHECK, "SAME.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_same_t * accepts any of them. */
typedef ld_same_t ld_same0_t;
typedef ld_same_t ld_same1_t;

/* SAME0 @ 0x4005D000 */
#define LD_SAME0_BASE (0x4005D000UL)
REGFORGE_MAYBE_UNUSED static ld_same_t *const LD_SAME0 = (ld_same_t *)LD_SAME0_BASE;

/* SAME0.CR */
#define LD_SAME0_CR (LD_SAME0->CR)

/* SAME1 @ 0x4005D000 */
#define LD_SAME1_BASE (0x4005D000UL)
REGFORGE_MAYBE_UNUSED static ld_same_t *const LD_SAME1 = (ld_same_t *)LD_SAME1_BASE;

/* SAME1.CR */
#define LD_SAME1_CR (LD_SAME1->CR)


/* -------------------------------------------------------------------------- */
/* PWMX */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_PWMX_CH_OFFSET      (0x00000000UL)
#define LD_PWMX_CH_STRIDE      (0x00000008UL)
#define LD_PWMX_CH_COUNT       (4U)
#define LD_PWMX_RESERVED0_SIZE (0x00000004UL)
#define LD_PWMX_RESERVED1_SIZE (0x00000004UL)
#define LD_PWMX_RESERVED2_SIZE (0x00000004UL)
#define LD_PWMX_RESERVED3_SIZE (0x00000004UL)
#define LD_PWMX_SIZE           (0x00000020UL)

typedef struct {
    volatile uint32_t CH0;                                /* 0x00 */
    uint8_t           RESERVED0[LD_PWMX_RESERVED0_SIZE];  /* 0x04  (reserved) */
    volatile uint32_t CH1;                                /* 0x08 */
    uint8_t           RESERVED1[LD_PWMX_RESERVED1_SIZE];  /* 0x0C  (reserved) */
    volatile uint32_t CH2;                                /* 0x10 */
    uint8_t           RESERVED2[LD_PWMX_RESERVED2_SIZE];  /* 0x14  (reserved) */
    volatile uint32_t CH3;                                /* 0x18 */
    uint8_t           RESERVED3[LD_PWMX_RESERVED3_SIZE];  /* 0x1C  (reserved) */
} ld_pwmx_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_pwmx_t, CH0) == LD_PWMX_CH_OFFSET + 0U * LD_PWMX_CH_STRIDE, LD_PWMX_CH0_OFFSET_CHECK, "PWMX.CH0 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_pwmx_t, CH1) == LD_PWMX_CH_OFFSET + 1U * LD_PWMX_CH_STRIDE, LD_PWMX_CH1_OFFSET_CHECK, "PWMX.CH1 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_pwmx_t, CH2) == LD_PWMX_CH_OFFSET + 2U * LD_PWMX_CH_STRIDE, LD_PWMX_CH2_OFFSET_CHECK, "PWMX.CH2 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_pwmx_t, CH3) == LD_PWMX_CH_OFFSET + 3U * LD_PWMX_CH_STRIDE, LD_PWMX_CH3_OFFSET_CHECK, "PWMX.CH3 offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_pwmx_t) == LD_PWMX_SIZE, LD_PWMX_SIZE_CHECK, "PWMX struct size vs addressBlock");

/* PWMX @ 0x4005E000 */
#define LD_PWMX_BASE (0x4005E000UL)
REGFORGE_MAYBE_UNUSED static ld_pwmx_t *const LD_PWMX = (ld_pwmx_t *)LD_PWMX_BASE;

/* PWMX.CH[4] */
#define LD_PWMX_CH(ch_index) (*(volatile uint32_t *)(LD_PWMX_BASE + LD_PWMX_CH_OFFSET + (ch_index) * LD_PWMX_CH_STRIDE))


/* -------------------------------------------------------------------------- */
/* FIFOX */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_FIFOX_DATA0_OFFSET  (0x00000000UL)
#define LD_FIFOX_DATA1_OFFSET  (0x00000004UL)
#define LD_FIFOX_DATA2_OFFSET  (0x00000008UL)
#define LD_FIFOX_DATA3_OFFSET  (0x0000000CUL)
#define LD_FIFOX_DATA4_OFFSET  (0x00000010UL)
#define LD_FIFOX_DATA5_OFFSET  (0x00000014UL)
#define LD_FIFOX_DATA6_OFFSET  (0x00000018UL)
#define LD_FIFOX_DATA7_OFFSET  (0x0000001CUL)
#define LD_FIFOX_DATA8_OFFSET  (0x00000020UL)
#define LD_FIFOX_DATA9_OFFSET  (0x00000024UL)
#define LD_FIFOX_DATA10_OFFSET (0x00000028UL)
#define LD_FIFOX_DATA11_OFFSET (0x0000002CUL)
#define LD_FIFOX_DATA12_OFFSET (0x00000030UL)
#define LD_FIFOX_DATA13_OFFSET (0x00000034UL)
#define LD_FIFOX_DATA14_OFFSET (0x00000038UL)
#define LD_FIFOX_DATA15_OFFSET (0x0000003CUL)
#define LD_FIFOX_SIZE          (0x00000040UL)

typedef struct {
    volatile uint32_t DATA0;   /* 0x00 */
    volatile uint32_t DATA1;   /* 0x04 */
    volatile uint32_t DATA2;   /* 0x08 */
    volatile uint32_t DATA3;   /* 0x0C */
    volatile uint32_t DATA4;   /* 0x10 */
    volatile uint32_t DATA5;   /* 0x14 */
    volatile uint32_t DATA6;   /* 0x18 */
    volatile uint32_t DATA7;   /* 0x1C */
    volatile uint32_t DATA8;   /* 0x20 */
    volatile uint32_t DATA9;   /* 0x24 */
    volatile uint32_t DATA10;  /* 0x28 */
    volatile uint32_t DATA11;  /* 0x2C */
    volatile uint32_t DATA12;  /* 0x30 */
    volatile uint32_t DATA13;  /* 0x34 */
    volatile uint32_t DATA14;  /* 0x38 */
    volatile uint32_t DATA15;  /* 0x3C */
} ld_fifox_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA0) == LD_FIFOX_DATA0_OFFSET, LD_FIFOX_DATA0_OFFSET_CHECK, "FIFOX.DATA0 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA1) == LD_FIFOX_DATA1_OFFSET, LD_FIFOX_DATA1_OFFSET_CHECK, "FIFOX.DATA1 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA2) == LD_FIFOX_DATA2_OFFSET, LD_FIFOX_DATA2_OFFSET_CHECK, "FIFOX.DATA2 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA3) == LD_FIFOX_DATA3_OFFSET, LD_FIFOX_DATA3_OFFSET_CHECK, "FIFOX.DATA3 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA4) == LD_FIFOX_DATA4_OFFSET, LD_FIFOX_DATA4_OFFSET_CHECK, "FIFOX.DATA4 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA5) == LD_FIFOX_DATA5_OFFSET, LD_FIFOX_DATA5_OFFSET_CHECK, "FIFOX.DATA5 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA6) == LD_FIFOX_DATA6_OFFSET, LD_FIFOX_DATA6_OFFSET_CHECK, "FIFOX.DATA6 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA7) == LD_FIFOX_DATA7_OFFSET, LD_FIFOX_DATA7_OFFSET_CHECK, "FIFOX.DATA7 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA8) == LD_FIFOX_DATA8_OFFSET, LD_FIFOX_DATA8_OFFSET_CHECK, "FIFOX.DATA8 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA9) == LD_FIFOX_DATA9_OFFSET, LD_FIFOX_DATA9_OFFSET_CHECK, "FIFOX.DATA9 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA10) == LD_FIFOX_DATA10_OFFSET, LD_FIFOX_DATA10_OFFSET_CHECK, "FIFOX.DATA10 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA11) == LD_FIFOX_DATA11_OFFSET, LD_FIFOX_DATA11_OFFSET_CHECK, "FIFOX.DATA11 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA12) == LD_FIFOX_DATA12_OFFSET, LD_FIFOX_DATA12_OFFSET_CHECK, "FIFOX.DATA12 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA13) == LD_FIFOX_DATA13_OFFSET, LD_FIFOX_DATA13_OFFSET_CHECK, "FIFOX.DATA13 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA14) == LD_FIFOX_DATA14_OFFSET, LD_FIFOX_DATA14_OFFSET_CHECK, "FIFOX.DATA14 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifox_t, DATA15) == LD_FIFOX_DATA15_OFFSET, LD_FIFOX_DATA15_OFFSET_CHECK, "FIFOX.DATA15 offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_fifox_t) == LD_FIFOX_SIZE, LD_FIFOX_SIZE_CHECK, "FIFOX struct size vs addressBlock");

/* FIFOX @ 0x4005F000 */
#define LD_FIFOX_BASE (0x4005F000UL)
REGFORGE_MAYBE_UNUSED static ld_fifox_t *const LD_FIFOX = (ld_fifox_t *)LD_FIFOX_BASE;

/* FIFOX.DATA0 */
#define LD_FIFOX_DATA0 (LD_FIFOX->DATA0)

/* FIFOX.DATA1 */
#define LD_FIFOX_DATA1 (LD_FIFOX->DATA1)

/* FIFOX.DATA2 */
#define LD_FIFOX_DATA2 (LD_FIFOX->DATA2)

/* FIFOX.DATA3 */
#define LD_FIFOX_DATA3 (LD_FIFOX->DATA3)

/* FIFOX.DATA4 */
#define LD_FIFOX_DATA4 (LD_FIFOX->DATA4)

/* FIFOX.DATA5 */
#define LD_FIFOX_DATA5 (LD_FIFOX->DATA5)

/* FIFOX.DATA6 */
#define LD_FIFOX_DATA6 (LD_FIFOX->DATA6)

/* FIFOX.DATA7 */
#define LD_FIFOX_DATA7 (LD_FIFOX->DATA7)

/* FIFOX.DATA8 */
#define LD_FIFOX_DATA8 (LD_FIFOX->DATA8)

/* FIFOX.DATA9 */
#define LD_FIFOX_DATA9 (LD_FIFOX->DATA9)

/* FIFOX.DATA10 */
#define LD_FIFOX_DATA10 (LD_FIFOX->DATA10)

/* FIFOX.DATA11 */
#define LD_FIFOX_DATA11 (LD_FIFOX->DATA11)

/* FIFOX.DATA12 */
#define LD_FIFOX_DATA12 (LD_FIFOX->DATA12)

/* FIFOX.DATA13 */
#define LD_FIFOX_DATA13 (LD_FIFOX->DATA13)

/* FIFOX.DATA14 */
#define LD_FIFOX_DATA14 (LD_FIFOX->DATA14)

/* FIFOX.DATA15 */
#define LD_FIFOX_DATA15 (LD_FIFOX->DATA15)


/* -------------------------------------------------------------------------- */
/* OVL (family: OVL0, OVL1) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_OVL_CR_OFFSET      (0x00000000UL)
#define LD_OVL_RESERVED0_SIZE (0x000003FCUL)
#define LD_OVL_SIZE           (0x00000400UL)

typedef struct {
    volatile uint32_t CR;                                /* 0x00 */
    uint8_t           RESERVED0[LD_OVL_RESERVED0_SIZE];  /* 0x04  (reserved) */
} ld_ovl_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_ovl_t, CR) == LD_OVL_CR_OFFSET, LD_OVL_CR_OFFSET_CHECK, "OVL.CR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_ovl_t) == LD_OVL_SIZE, LD_OVL_SIZE_CHECK, "OVL struct size vs addressBlock");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_ovl_t * accepts any of them. */
typedef ld_ovl_t ld_ovl0_t;
typedef ld_ovl_t ld_ovl1_t;

/* OVL0 @ 0x40060000 */
#define LD_OVL0_BASE (0x40060000UL)
REGFORGE_MAYBE_UNUSED static ld_ovl_t *const LD_OVL0 = (ld_ovl_t *)LD_OVL0_BASE;

/* OVL0.CR */
#define LD_OVL0_CR (LD_OVL0->CR)

/* OVL1 @ 0x40060100 */
#define LD_OVL1_BASE (0x40060100UL)
REGFORGE_MAYBE_UNUSED static ld_ovl_t *const LD_OVL1 = (ld_ovl_t *)LD_OVL1_BASE;

/* OVL1.CR */
#define LD_OVL1_CR (LD_OVL1->CR)


/* -------------------------------------------------------------------------- */
/* SER (family: SER0, SER1, SER2, SER3, SERX0, SERX1, SERX2, SERX3) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_SER_CR_OFFSET      (0x00000000UL)
#define LD_SER_RESERVED0_SIZE (0x000000FCUL)
#define LD_SER_SIZE           (0x00000100UL)

typedef struct {
    volatile uint32_t CR;                                /* 0x00 */
    uint8_t           RESERVED0[LD_SER_RESERVED0_SIZE];  /* 0x04  (reserved) */
} ld_ser_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_ser_t, CR) == LD_SER_CR_OFFSET, LD_SER_CR_OFFSET_CHECK, "SER.CR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_ser_t) == LD_SER_SIZE, LD_SER_SIZE_CHECK, "SER struct size vs addressBlock");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_ser_t * accepts any of them. */
typedef ld_ser_t ld_ser0_t;
typedef ld_ser_t ld_ser1_t;
typedef ld_ser_t ld_ser2_t;
typedef ld_ser_t ld_ser3_t;
typedef ld_ser_t ld_serx0_t;
typedef ld_ser_t ld_serx1_t;
typedef ld_ser_t ld_serx2_t;
typedef ld_ser_t ld_serx3_t;

/* SER0 @ 0x40061000 */
#define LD_SER0_BASE (0x40061000UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SER0 = (ld_ser_t *)LD_SER0_BASE;

/* SER0.CR */
#define LD_SER0_CR (LD_SER0->CR)

/* SER1 @ 0x40061100 */
#define LD_SER1_BASE (0x40061100UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SER1 = (ld_ser_t *)LD_SER1_BASE;

/* SER1.CR */
#define LD_SER1_CR (LD_SER1->CR)

/* SER2 @ 0x40061200 */
#define LD_SER2_BASE (0x40061200UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SER2 = (ld_ser_t *)LD_SER2_BASE;

/* SER2.CR */
#define LD_SER2_CR (LD_SER2->CR)

/* SER3 @ 0x40061300 */
#define LD_SER3_BASE (0x40061300UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SER3 = (ld_ser_t *)LD_SER3_BASE;

/* SER3.CR */
#define LD_SER3_CR (LD_SER3->CR)

/* SERX0 @ 0x40063000 */
#define LD_SERX0_BASE (0x40063000UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SERX0 = (ld_ser_t *)LD_SERX0_BASE;

/* SERX0.CR */
#define LD_SERX0_CR (LD_SERX0->CR)

/* SERX1 @ 0x40063200 */
#define LD_SERX1_BASE (0x40063200UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SERX1 = (ld_ser_t *)LD_SERX1_BASE;

/* SERX1.CR */
#define LD_SERX1_CR (LD_SERX1->CR)

/* SERX2 @ 0x40063400 */
#define LD_SERX2_BASE (0x40063400UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SERX2 = (ld_ser_t *)LD_SERX2_BASE;

/* SERX2.CR */
#define LD_SERX2_CR (LD_SERX2->CR)

/* SERX3 @ 0x40063600 */
#define LD_SERX3_BASE (0x40063600UL)
REGFORGE_MAYBE_UNUSED static ld_ser_t *const LD_SERX3 = (ld_ser_t *)LD_SERX3_BASE;

/* SERX3.CR */
#define LD_SERX3_CR (LD_SERX3->CR)


/* -------------------------------------------------------------------------- */
/* SPIX */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_SPIX_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_spix_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_spix_t, CR) == LD_SPIX_CR_OFFSET, LD_SPIX_CR_OFFSET_CHECK, "SPIX.CR offset");

/* SPIX @ 0x40061380 */
#define LD_SPIX_BASE (0x40061380UL)
REGFORGE_MAYBE_UNUSED static ld_spix_t *const LD_SPIX = (ld_spix_t *)LD_SPIX_BASE;

/* SPIX.CR */
#define LD_SPIX_CR (LD_SPIX->CR)


/* -------------------------------------------------------------------------- */
/* TMRU (family: TMRU0, TMRU1) */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_TMRU_CR_OFFSET (0x00000000UL)

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_tmru_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmru_t, CR) == LD_TMRU_CR_OFFSET, LD_TMRU_CR_OFFSET_CHECK, "TMRU.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_tmru_t * accepts any of them. */
typedef ld_tmru_t ld_tmru0_t;
typedef ld_tmru_t ld_tmru1_t;

/* TMRU0 @ 0x40064000 */
#define LD_TMRU0_BASE (0x40064000UL)
REGFORGE_MAYBE_UNUSED static ld_tmru_t *const LD_TMRU0 = (ld_tmru_t *)LD_TMRU0_BASE;
#define LD_TMRU_IRQ_IRQ LD_TMRU_IRQ_IRQn  /* vector 43 */

/* TMRU0.CR */
#define LD_TMRU0_CR (LD_TMRU0->CR)

/* TMRU1 @ 0x40064100 */
#define LD_TMRU1_BASE (0x40064100UL)
REGFORGE_MAYBE_UNUSED static ld_tmru_t *const LD_TMRU1 = (ld_tmru_t *)LD_TMRU1_BASE;

/* TMRU1.CR */
#define LD_TMRU1_CR (LD_TMRU1->CR)


/* -------------------------------------------------------------------------- */
/* ALTX */

/* Layout constants: byte offsets from an instance's base; a cluster's members
 * are relative to one element of that cluster. Every assert below refers to
 * these, so each number is written once; the register macros go through the
 * typed instance and repeat none of them. */
#define LD_ALTX_A_OFFSET       (0x00000000UL)
#define LD_ALTX_A_SIZE         (0x00000004UL)
#define LD_ALTX_RESERVED0_SIZE (0x00000004UL)
#define LD_ALTX_B_OFFSET       (0x00000008UL)
#define LD_ALTX_RESERVED1_SIZE (0x00000004UL)
#define LD_ALTX_C_OFFSET       (0x00000010UL)
#define LD_ALTX_CCR_OFFSET     (0x00000014UL)
#define LD_ALTX_CCR_X_OFFSET   (0x00000018UL)
#define LD_ALTX_CCR_X_SIZE     (0x00000004UL)
#define LD_ALTX_RESERVED2_SIZE (0x00000004UL)
#define LD_ALTX_D_OFFSET       (0x00000020UL)
#define LD_ALTX_RESERVED3_SIZE (0x00000004UL)
#define LD_ALTX_F_OFFSET       (0x00000028UL)
#define LD_ALTX_F_STRIDE       (0x00000004UL)
#define LD_ALTX_F_COUNT        (2U)
#define LD_ALTX_G_OFFSET       (0x00000030UL)
#define LD_ALTX_G_STRIDE       (0x00000004UL)
#define LD_ALTX_G_COUNT        (3U)
#define LD_ALTX_RESERVED4_SIZE (0x00000004UL)
#define LD_ALTX_SIZE           (0x00000040UL)

typedef struct {
    union {
        volatile uint32_t Out;  /* 0x00 */
        volatile uint32_t In;   /* 0x00 */
    } A;  /* 0x00  one register, 2 views */
    uint8_t           RESERVED0[LD_ALTX_RESERVED0_SIZE];  /* 0x04  (reserved) */
    volatile uint32_t B;                                  /* 0x08 */
    uint8_t           RESERVED1[LD_ALTX_RESERVED1_SIZE];  /* 0x0C  (reserved) */
    volatile uint32_t C;                                  /* 0x10 */
    volatile uint32_t CCR;                                /* 0x14 */
    union {
        volatile uint32_t CCR_X;  /* 0x18 */
        volatile uint32_t CCR_Y;  /* 0x18 */
    } CCR_X;  /* 0x18  one register, 2 views */
    uint8_t           RESERVED2[LD_ALTX_RESERVED2_SIZE];  /* 0x1C  (reserved) */
    volatile uint32_t D;                                  /* 0x20 */
    uint8_t           RESERVED3[LD_ALTX_RESERVED3_SIZE];  /* 0x24  (reserved) */
    volatile uint32_t F[LD_ALTX_F_COUNT];                 /* 0x28 */
    volatile uint32_t G[LD_ALTX_G_COUNT];                 /* 0x30 */
    uint8_t           RESERVED4[LD_ALTX_RESERVED4_SIZE];  /* 0x3C  (reserved) */
} ld_altx_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, A) == LD_ALTX_A_OFFSET, LD_ALTX_A_OFFSET_CHECK, "ALTX.A offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, B) == LD_ALTX_B_OFFSET, LD_ALTX_B_OFFSET_CHECK, "ALTX.B offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, C) == LD_ALTX_C_OFFSET, LD_ALTX_C_OFFSET_CHECK, "ALTX.C offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, CCR) == LD_ALTX_CCR_OFFSET, LD_ALTX_CCR_OFFSET_CHECK, "ALTX.CCR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, CCR_X) == LD_ALTX_CCR_X_OFFSET, LD_ALTX_CCR_X_OFFSET_CHECK, "ALTX.CCR_X offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, D) == LD_ALTX_D_OFFSET, LD_ALTX_D_OFFSET_CHECK, "ALTX.D offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, F) == LD_ALTX_F_OFFSET, LD_ALTX_F_OFFSET_CHECK, "ALTX.F offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, G) == LD_ALTX_G_OFFSET, LD_ALTX_G_OFFSET_CHECK, "ALTX.G offset");
REGFORGE_STATIC_ASSERT(sizeof(((ld_altx_t *)0)->F) == LD_ALTX_F_COUNT * LD_ALTX_F_STRIDE, LD_ALTX_F_ARRAY_CHECK, "ALTX.F array size");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, F) + (LD_ALTX_F_COUNT - 1U) * sizeof(((ld_altx_t *)0)->F[0]) == LD_ALTX_F_OFFSET + (LD_ALTX_F_COUNT - 1U) * LD_ALTX_F_STRIDE, LD_ALTX_F_LAST_CHECK, "ALTX.F[1] offset via the struct");
REGFORGE_STATIC_ASSERT(sizeof(((ld_altx_t *)0)->G) == LD_ALTX_G_COUNT * LD_ALTX_G_STRIDE, LD_ALTX_G_ARRAY_CHECK, "ALTX.G array size");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, G) + (LD_ALTX_G_COUNT - 1U) * sizeof(((ld_altx_t *)0)->G[0]) == LD_ALTX_G_OFFSET + (LD_ALTX_G_COUNT - 1U) * LD_ALTX_G_STRIDE, LD_ALTX_G_LAST_CHECK, "ALTX.G[2] offset via the struct");
REGFORGE_STATIC_ASSERT(sizeof(((ld_altx_t *)0)->A) == LD_ALTX_A_SIZE, LD_ALTX_A_SIZE_CHECK, "ALTX.A union size");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, A.Out) == LD_ALTX_A_OFFSET, LD_ALTX_A_OUT_OFFSET_CHECK, "ALTX.A.Out offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, A.In) == LD_ALTX_A_OFFSET, LD_ALTX_A_IN_OFFSET_CHECK, "ALTX.A.In offset");
REGFORGE_STATIC_ASSERT(sizeof(((ld_altx_t *)0)->CCR_X) == LD_ALTX_CCR_X_SIZE, LD_ALTX_CCR_X_SIZE_CHECK, "ALTX.CCR_X union size");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, CCR_X.CCR_X) == LD_ALTX_CCR_X_OFFSET, LD_ALTX_CCR_X_CCR_X_OFFSET_CHECK, "ALTX.CCR_X.CCR_X offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_altx_t, CCR_X.CCR_Y) == LD_ALTX_CCR_X_OFFSET, LD_ALTX_CCR_X_CCR_Y_OFFSET_CHECK, "ALTX.CCR_X.CCR_Y offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_altx_t) == LD_ALTX_SIZE, LD_ALTX_SIZE_CHECK, "ALTX struct size vs addressBlock");

/* ALTX @ 0x40070000 */
#define LD_ALTX_BASE (0x40070000UL)
REGFORGE_MAYBE_UNUSED static ld_altx_t *const LD_ALTX = (ld_altx_t *)LD_ALTX_BASE;

/* ALTX.A_Out  [alternate: A_In] */
#define LD_ALTX_A_OUT (LD_ALTX->A.Out)
#define LD_ALTX_A_OUT_RESET_VALUE (0x00000000UL)

/* ALTX.A_In  [alternate: A_Out] */
#define LD_ALTX_A_IN (LD_ALTX->A.In)
#define LD_ALTX_A_IN_RESET_VALUE (0x000000FFUL)

/* ALTX.B */
#define LD_ALTX_B (LD_ALTX->B)

/* ALTX.C */
#define LD_ALTX_C (LD_ALTX->C)

/* ALTX.CCR */
#define LD_ALTX_CCR (LD_ALTX->CCR)

/* ALTX.CCR_X  [alternate: CCR_Y] */
#define LD_ALTX_CCR_X (LD_ALTX->CCR_X.CCR_X)

/* ALTX.CCR_Y  [alternate: CCR_X] */
#define LD_ALTX_CCR_Y (LD_ALTX->CCR_X.CCR_Y)

/* ALTX.D */
#define LD_ALTX_D (LD_ALTX->D)

/* ALTX.F[2] */
#define LD_ALTX_F(f_index) (LD_ALTX->F[(f_index)])

/* ALTX.G[3] */
#define LD_ALTX_G(g_index) (LD_ALTX->G[(g_index)])

#endif /* REGFORGE_LINTDEMO_H */
