/*
 * LintDemo register definitions.
 *
 * Device:  LintDemo (DemoCorp)
 *
 * Source:  lint_demo.svd
 * sha256:  586335a2ece439cc6d1d4fb9fa7d61f6e45d7400f7d9f7edd86dba535d01cbf9
 * Command: regforge tests/fixtures/svd/lint_demo.svd -o tests/golden/c/lint_demo.h
 * Generated by regforge 0.0.1 -- do not edit.
 */
#ifndef REGFORGE_LINTDEMO_H
#define REGFORGE_LINTDEMO_H

#include <stdint.h>
#include <stddef.h>
#include <limits.h>

/* ========================================================================== */
/* Compiler compatibility */
/* ========================================================================== */
#ifndef REGFORGE_COMPAT_H
#define REGFORGE_COMPAT_H

/* Language standard as a comparable number (0 if not a Standard C compiler). */
#if defined(__STDC_VERSION__)
#  define REGFORGE_STDC __STDC_VERSION__
#else
#  define REGFORGE_STDC 0L
#endif

/* REGFORGE_STATIC_ASSERT(cond, tag, msg) -- compile-time check.
 * C++11+ and C11/C23 have a language construct; older dialects fall back to a
 * negative-array typedef named REGFORGE_assert_<tag>. `tag` must be unique per
 * translation unit -- regforge passes a device-namespaced tag. */
#if defined(__cplusplus) && (__cplusplus >= 201103L)
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) static_assert(cond, msg)
#elif REGFORGE_STDC >= 201112L
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) _Static_assert(cond, msg)
#else
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) \
       typedef char REGFORGE_assert_##tag[(cond) ? 1 : -1]
#endif

/* REGFORGE_INLINE -- inline with internal linkage.
 * `inline` is C99/C++; on C89 degrade to `static`, plus the unused attribute
 * (on compilers that support it) so an unreferenced helper stays warning-free. */
#if defined(__cplusplus) || REGFORGE_STDC >= 199901L
#  define REGFORGE_INLINE static inline
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_INLINE static __attribute__((unused))
#else
#  define REGFORGE_INLINE static
#endif

/* REGFORGE_MAYBE_UNUSED -- suppress "defined but not used" on an entity a given
 * translation unit may legitimately not reference. Used as a *prefix* on the
 * declaration (required by [[maybe_unused]]; also valid for __attribute__). */
#if defined(__cplusplus) && (__cplusplus >= 201703L)
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]
#elif REGFORGE_STDC >= 202311L
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]              /* C23 */
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_MAYBE_UNUSED __attribute__((unused))       /* GCC/Clang/armclang/armcc5/IAR8+ */
#else
#  define REGFORGE_MAYBE_UNUSED                                /* MSVC (no such warning) + exotic */
#endif

#endif /* REGFORGE_COMPAT_H */

/* ========================================================================== */
/* Device */
/* ========================================================================== */
#define LINTDEMO_ADDRESS_UNIT_BITS 8
REGFORGE_STATIC_ASSERT(CHAR_BIT == LINTDEMO_ADDRESS_UNIT_BITS, LINTDEMO_address_unit_bits,
    "regforge: this header targets 8-bit address units; "
    "the compiler's CHAR_BIT disagrees -- regenerate with a matching emitter mode.");

#define LINTDEMO_BUS_WIDTH 32
#define LINTDEMO_SVD_SHA256 "586335a2ece439cc6d1d4fb9fa7d61f6e45d7400f7d9f7edd86dba535d01cbf9"

/* ========================================================================== */
/* Peripherals */
/* ========================================================================== */

/* -------------------------------------------------------------------------- */
/* UART */

typedef struct {
    volatile uint32_t DR;               /* 0x00 */
    uint8_t           RESERVED0[1020];  /* 0x04  (reserved) */
} ld_uart_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_uart_t, DR) == 0x00, LD_UART_DR_offset, "UART.DR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_uart_t) == 0x400, LD_UART_SIZE, "UART struct size vs addressBlock");

/* UART @ 0x40004000 */
#define LD_UART_BASE (0x40004000UL)
REGFORGE_MAYBE_UNUSED static ld_uart_t *const LD_UART = (ld_uart_t *)LD_UART_BASE;

/* UART.DR */
#define LD_UART_DR (*(volatile uint32_t *)(LD_UART_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* TIMER */

typedef struct {
    volatile uint32_t CR;              /* 0x00 */
    uint8_t           RESERVED0[252];  /* 0x04  (reserved) */
} ld_timer_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_timer_t, CR) == 0x00, LD_TIMER_CR_offset, "TIMER.CR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_timer_t) == 0x100, LD_TIMER_SIZE, "TIMER struct size vs addressBlock");

/* TIMER @ 0x40004200 */
#define LD_TIMER_BASE (0x40004200UL)
REGFORGE_MAYBE_UNUSED static ld_timer_t *const LD_TIMER = (ld_timer_t *)LD_TIMER_BASE;

/* TIMER.CR */
#define LD_TIMER_CR (*(volatile uint32_t *)(LD_TIMER_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* FLASH */

typedef struct {
    volatile uint32_t CR;             /* 0x00 */
    uint8_t           RESERVED0[60];  /* 0x04  (reserved) */
    volatile uint32_t FAR;            /* 0x40 */
} ld_flash_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_flash_t, CR) == 0x00, LD_FLASH_CR_offset, "FLASH.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_flash_t, FAR) == 0x40, LD_FLASH_FAR_offset, "FLASH.FAR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_flash_t) == 0x44, LD_FLASH_SIZE, "FLASH struct size vs addressBlock");

/* FLASH @ 0x40010000 */
#define LD_FLASH_BASE (0x40010000UL)
REGFORGE_MAYBE_UNUSED static ld_flash_t *const LD_FLASH = (ld_flash_t *)LD_FLASH_BASE;

/* FLASH.CR */
#define LD_FLASH_CR (*(volatile uint32_t *)(LD_FLASH_BASE + 0x00000000UL))

/* FLASH.FAR */
#define LD_FLASH_FAR (*(volatile uint32_t *)(LD_FLASH_BASE + 0x00000040UL))


/* -------------------------------------------------------------------------- */
/* DMA */

typedef struct {
    volatile uint32_t CR;             /* 0x00 */
    uint8_t           RESERVED0[12];  /* 0x04  (reserved) */
    volatile uint32_t BUFFER0[8];     /* 0x10  (buffer) */
} ld_dma_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dma_t, CR) == 0x00, LD_DMA_CR_offset, "DMA.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_dma_t, BUFFER0) == 0x10, LD_DMA_BUFFER0_offset, "DMA.BUFFER0 offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_dma_t) == 0x30, LD_DMA_SIZE, "DMA struct size vs addressBlock");

/* DMA @ 0x40020000 */
#define LD_DMA_BASE (0x40020000UL)
REGFORGE_MAYBE_UNUSED static ld_dma_t *const LD_DMA = (ld_dma_t *)LD_DMA_BASE;

/* DMA.CR */
#define LD_DMA_CR (*(volatile uint32_t *)(LD_DMA_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* MISC */

typedef struct {
    volatile uint32_t REG;  /* 0x00 */
} ld_misc_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_misc_t, REG) == 0x00, LD_MISC_REG_offset, "MISC.REG offset");

/* MISC @ 0x40030000 */
#define LD_MISC_BASE (0x40030000UL)
REGFORGE_MAYBE_UNUSED static ld_misc_t *const LD_MISC = (ld_misc_t *)LD_MISC_BASE;

/* MISC.REG */
#define LD_MISC_REG (*(volatile uint32_t *)(LD_MISC_BASE + 0x00000000UL))

#endif /* REGFORGE_LINTDEMO_H */
