/*
 * LintDemo register definitions.
 *
 * Device:  LintDemo (DemoCorp)
 *
 * Source:  lint_demo.svd
 * sha256:  837026fd174a31dc87cfc980930f816d16d6a7ba52db72b2b0671eab70e631b3
 * Command: regforge tests/fixtures/svd/lint_demo.svd -o tests/golden/c/lint_demo.h
 * Generated by regforge 0.0.1 -- do not edit.
 */
#ifndef REGFORGE_LINTDEMO_H
#define REGFORGE_LINTDEMO_H

#include <stdint.h>
#include <stddef.h>
#include <limits.h>

/* ========================================================================== */
/* Compiler compatibility */
/* ========================================================================== */
#ifndef REGFORGE_COMPAT_H
#define REGFORGE_COMPAT_H

/* Language standard as a comparable number (0 if not a Standard C compiler). */
#if defined(__STDC_VERSION__)
#  define REGFORGE_STDC __STDC_VERSION__
#else
#  define REGFORGE_STDC 0L
#endif

/* REGFORGE_STATIC_ASSERT(cond, tag, msg) -- compile-time check.
 * C++11+ and C11/C23 have a language construct; older dialects fall back to a
 * negative-array typedef named REGFORGE_assert_<tag>. `tag` must be unique per
 * translation unit -- regforge passes a device-namespaced tag. */
#if defined(__cplusplus) && (__cplusplus >= 201103L)
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) static_assert(cond, msg)
#elif REGFORGE_STDC >= 201112L
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) _Static_assert(cond, msg)
#else
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) \
       typedef char REGFORGE_assert_##tag[(cond) ? 1 : -1]
#endif

/* REGFORGE_INLINE -- inline with internal linkage.
 * `inline` is C99/C++; on C89 degrade to `static`, plus the unused attribute
 * (on compilers that support it) so an unreferenced helper stays warning-free. */
#if defined(__cplusplus) || REGFORGE_STDC >= 199901L
#  define REGFORGE_INLINE static inline
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_INLINE static __attribute__((unused))
#else
#  define REGFORGE_INLINE static
#endif

/* REGFORGE_MAYBE_UNUSED -- suppress "defined but not used" on an entity a given
 * translation unit may legitimately not reference. Used as a *prefix* on the
 * declaration (required by [[maybe_unused]]; also valid for __attribute__). */
#if defined(__cplusplus) && (__cplusplus >= 201703L)
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]
#elif REGFORGE_STDC >= 202311L
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]              /* C23 */
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_MAYBE_UNUSED __attribute__((unused))       /* GCC/Clang/armclang/armcc5/IAR8+ */
#else
#  define REGFORGE_MAYBE_UNUSED                                /* MSVC (no such warning) + exotic */
#endif

#endif /* REGFORGE_COMPAT_H */

/* ========================================================================== */
/* Device */
/* ========================================================================== */
#define LINTDEMO_ADDRESS_UNIT_BITS 8
REGFORGE_STATIC_ASSERT(CHAR_BIT == LINTDEMO_ADDRESS_UNIT_BITS, LINTDEMO_address_unit_bits,
    "regforge: this header targets 8-bit address units; "
    "the compiler's CHAR_BIT disagrees -- regenerate with a matching emitter mode.");

#define LINTDEMO_BUS_WIDTH 32
#define LINTDEMO_SVD_SHA256 "837026fd174a31dc87cfc980930f816d16d6a7ba52db72b2b0671eab70e631b3"

/* ========================================================================== */
/* Interrupts */
/* ========================================================================== */
/* Device interrupt vector numbers (CMSIS IRQn_Type equivalent). Peripherals
 * link to these via their <NAME>_IRQ constants; the NVIC helpers take this
 * enum, so a raw int can't stand in for a vector number. */
typedef enum {
    LD_ADCA_IRQn  = 40,
    LD_TMRX0_IRQn = 41,
    LD_TMRX1_IRQn = 41
} ld_irqn_e;

/* ========================================================================== */
/* Peripherals */
/* ========================================================================== */

/* -------------------------------------------------------------------------- */
/* UART */

typedef struct {
    volatile uint32_t DR;               /* 0x00 */
    uint8_t           RESERVED0[1020];  /* 0x04  (reserved) */
} ld_uart_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_uart_t, DR) == 0x00, LD_UART_DR_offset, "UART.DR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_uart_t) == 0x400, LD_UART_SIZE, "UART struct size vs addressBlock");

/* UART @ 0x40004000 */
#define LD_UART_BASE (0x40004000UL)
REGFORGE_MAYBE_UNUSED static ld_uart_t *const LD_UART = (ld_uart_t *)LD_UART_BASE;

/* UART.DR */
#define LD_UART_DR (*(volatile uint32_t *)(LD_UART_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* TIMER */

typedef struct {
    volatile uint32_t CR;              /* 0x00 */
    uint8_t           RESERVED0[252];  /* 0x04  (reserved) */
} ld_timer_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_timer_t, CR) == 0x00, LD_TIMER_CR_offset, "TIMER.CR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_timer_t) == 0x100, LD_TIMER_SIZE, "TIMER struct size vs addressBlock");

/* TIMER @ 0x40004200 */
#define LD_TIMER_BASE (0x40004200UL)
REGFORGE_MAYBE_UNUSED static ld_timer_t *const LD_TIMER = (ld_timer_t *)LD_TIMER_BASE;

/* TIMER.CR */
#define LD_TIMER_CR (*(volatile uint32_t *)(LD_TIMER_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* FLASH */

typedef struct {
    volatile uint32_t CR;             /* 0x00 */
    uint8_t           RESERVED0[60];  /* 0x04  (reserved) */
    volatile uint32_t FAR;            /* 0x40 */
} ld_flash_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_flash_t, CR) == 0x00, LD_FLASH_CR_offset, "FLASH.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_flash_t, FAR) == 0x40, LD_FLASH_FAR_offset, "FLASH.FAR offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_flash_t) == 0x44, LD_FLASH_SIZE, "FLASH struct size vs addressBlock");

/* FLASH @ 0x40010000 */
#define LD_FLASH_BASE (0x40010000UL)
REGFORGE_MAYBE_UNUSED static ld_flash_t *const LD_FLASH = (ld_flash_t *)LD_FLASH_BASE;

/* FLASH.CR */
#define LD_FLASH_CR (*(volatile uint32_t *)(LD_FLASH_BASE + 0x00000000UL))

/* FLASH.FAR */
#define LD_FLASH_FAR (*(volatile uint32_t *)(LD_FLASH_BASE + 0x00000040UL))


/* -------------------------------------------------------------------------- */
/* DMA */

typedef struct {
    volatile uint32_t CR;             /* 0x00 */
    uint8_t           RESERVED0[12];  /* 0x04  (reserved) */
    volatile uint32_t BUFFER0[8];     /* 0x10  (buffer) */
} ld_dma_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dma_t, CR) == 0x00, LD_DMA_CR_offset, "DMA.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_dma_t, BUFFER0) == 0x10, LD_DMA_BUFFER0_offset, "DMA.BUFFER0 offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_dma_t) == 0x30, LD_DMA_SIZE, "DMA struct size vs addressBlock");

/* DMA @ 0x40020000 */
#define LD_DMA_BASE (0x40020000UL)
REGFORGE_MAYBE_UNUSED static ld_dma_t *const LD_DMA = (ld_dma_t *)LD_DMA_BASE;

/* DMA.CR */
#define LD_DMA_CR (*(volatile uint32_t *)(LD_DMA_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* FIFO */

typedef struct {
    volatile uint32_t CR;               /* 0x00 */
    uint8_t           RESERVED0[8188];  /* 0x04  (reserved) */
    volatile uint32_t DATA;             /* 0x2000 */
} ld_fifo_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_fifo_t, CR) == 0x00, LD_FIFO_CR_offset, "FIFO.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fifo_t, DATA) == 0x2000, LD_FIFO_DATA_offset, "FIFO.DATA offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_fifo_t) == 0x2004, LD_FIFO_SIZE, "FIFO struct size vs addressBlock");

/* FIFO @ 0x40040000 */
#define LD_FIFO_BASE (0x40040000UL)
REGFORGE_MAYBE_UNUSED static ld_fifo_t *const LD_FIFO = (ld_fifo_t *)LD_FIFO_BASE;

/* FIFO.CR */
#define LD_FIFO_CR (*(volatile uint32_t *)(LD_FIFO_BASE + 0x00000000UL))

/* FIFO.DATA */
#define LD_FIFO_DATA (*(volatile uint32_t *)(LD_FIFO_BASE + 0x00002000UL))


/* -------------------------------------------------------------------------- */
/* MISC */

typedef struct {
    volatile uint32_t REG;  /* 0x00 */
} ld_misc_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_misc_t, REG) == 0x00, LD_MISC_REG_offset, "MISC.REG offset");

/* MISC @ 0x40030000 */
#define LD_MISC_BASE (0x40030000UL)
REGFORGE_MAYBE_UNUSED static ld_misc_t *const LD_MISC = (ld_misc_t *)LD_MISC_BASE;

/* MISC.REG */
#define LD_MISC_REG (*(volatile uint32_t *)(LD_MISC_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* FPU_CPACR */

typedef struct {
    volatile uint32_t CPACR;  /* 0x00 */
} ld_fpu_cpacr_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_fpu_cpacr_t, CPACR) == 0x00, LD_FPU_CPACR_CPACR_offset, "FPU_CPACR.CPACR offset");

/* FPU_CPACR @ 0x40050000 */
#define LD_FPU_CPACR_BASE (0x40050000UL)
REGFORGE_MAYBE_UNUSED static ld_fpu_cpacr_t *const LD_FPU_CPACR = (ld_fpu_cpacr_t *)LD_FPU_CPACR_BASE;

/* FPU_CPACR.CPACR */
#define LD_FPU_CPACR_CPACR (*(volatile uint32_t *)(LD_FPU_CPACR_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* FPU */
/* family FPU: split 2 ways by layout (FPU_CPACR | FPU); first differs at CPACR */

typedef struct {
    volatile uint32_t FPCCR;  /* 0x00 */
    volatile uint32_t FPCAR;  /* 0x04 */
} ld_fpu_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_fpu_t, FPCCR) == 0x00, LD_FPU_FPCCR_offset, "FPU.FPCCR offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_fpu_t, FPCAR) == 0x04, LD_FPU_FPCAR_offset, "FPU.FPCAR offset");

/* FPU @ 0x40051000 */
#define LD_FPU_BASE (0x40051000UL)
REGFORGE_MAYBE_UNUSED static ld_fpu_t *const LD_FPU = (ld_fpu_t *)LD_FPU_BASE;

/* FPU.FPCCR */
#define LD_FPU_FPCCR (*(volatile uint32_t *)(LD_FPU_BASE + 0x00000000UL))

/* FPU.FPCAR */
#define LD_FPU_FPCAR (*(volatile uint32_t *)(LD_FPU_BASE + 0x00000004UL))


/* -------------------------------------------------------------------------- */
/* TMR */
/* family TMR: split 2 ways by layout (TMR0 | TIMER_ADV); first differs at RCR */

typedef struct {
    volatile uint32_t CR1;  /* 0x00 */
} ld_tmr_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmr_t, CR1) == 0x00, LD_TMR_CR1_offset, "TMR.CR1 offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_tmr_t * accepts any of them. */
typedef ld_tmr_t ld_tmr0_t;

/* TMR0 @ 0x40052000 */
#define LD_TMR0_BASE (0x40052000UL)
REGFORGE_MAYBE_UNUSED static ld_tmr_t *const LD_TMR0 = (ld_tmr_t *)LD_TMR0_BASE;

/* TMR0.CR1 */
#define LD_TMR0_CR1 (*(volatile uint32_t *)(LD_TMR0_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* TIMER_ADV */

typedef struct {
    volatile uint32_t CR1;  /* 0x00 */
    volatile uint32_t RCR;  /* 0x04 */
} ld_timer_adv_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_timer_adv_t, CR1) == 0x00, LD_TIMER_ADV_CR1_offset, "TIMER_ADV.CR1 offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_timer_adv_t, RCR) == 0x04, LD_TIMER_ADV_RCR_offset, "TIMER_ADV.RCR offset");

/* TIMER_ADV @ 0x40053000 */
#define LD_TIMER_ADV_BASE (0x40053000UL)
REGFORGE_MAYBE_UNUSED static ld_timer_adv_t *const LD_TIMER_ADV = (ld_timer_adv_t *)LD_TIMER_ADV_BASE;

/* TIMER_ADV.CR1 */
#define LD_TIMER_ADV_CR1 (*(volatile uint32_t *)(LD_TIMER_ADV_BASE + 0x00000000UL))

/* TIMER_ADV.RCR */
#define LD_TIMER_ADV_RCR (*(volatile uint32_t *)(LD_TIMER_ADV_BASE + 0x00000004UL))


/* -------------------------------------------------------------------------- */
/* ADCA (family: ADCA, ADCB) */

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_adca_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_adca_t, CR) == 0x00, LD_ADCA_CR_offset, "ADCA.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_adca_t * accepts any of them. */
typedef ld_adca_t ld_adcb_t;

/* ADCA @ 0x40054000 */
#define LD_ADCA_BASE (0x40054000UL)
REGFORGE_MAYBE_UNUSED static ld_adca_t *const LD_ADCA = (ld_adca_t *)LD_ADCA_BASE;
#define LD_ADCA_IRQ LD_ADCA_IRQn  /* vector 40 */

/* ADCA.CR */
#define LD_ADCA_CR (*(volatile uint32_t *)(LD_ADCA_BASE + 0x00000000UL))

/* ADCB @ 0x40055000 */
#define LD_ADCB_BASE (0x40055000UL)
REGFORGE_MAYBE_UNUSED static ld_adca_t *const LD_ADCB = (ld_adca_t *)LD_ADCB_BASE;

/* ADCB.CR */
#define LD_ADCB_CR (*(volatile uint32_t *)(LD_ADCB_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* TMRX (family: TMRX0, TMRX1) */

typedef struct {
    volatile uint32_t CR;  /* 0x00 */
} ld_tmrx_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_tmrx_t, CR) == 0x00, LD_TMRX_CR_offset, "TMRX.CR offset");

/* Per-instance names for the shared type, so a signature never has to know
 * which instances share a layout. Aliases, not distinct types: a function
 * taking ld_tmrx_t * accepts any of them. */
typedef ld_tmrx_t ld_tmrx0_t;
typedef ld_tmrx_t ld_tmrx1_t;

/* TMRX0 @ 0x40056000 */
#define LD_TMRX0_BASE (0x40056000UL)
REGFORGE_MAYBE_UNUSED static ld_tmrx_t *const LD_TMRX0 = (ld_tmrx_t *)LD_TMRX0_BASE;
#define LD_TMRX0_IRQ LD_TMRX0_IRQn  /* vector 41 -- shared with LD_TMRX1; demux in ISR */

/* TMRX0.CR */
#define LD_TMRX0_CR (*(volatile uint32_t *)(LD_TMRX0_BASE + 0x00000000UL))

/* TMRX1 @ 0x40056100 */
#define LD_TMRX1_BASE (0x40056100UL)
REGFORGE_MAYBE_UNUSED static ld_tmrx_t *const LD_TMRX1 = (ld_tmrx_t *)LD_TMRX1_BASE;
#define LD_TMRX1_IRQ LD_TMRX1_IRQn  /* vector 41 -- shared with LD_TMRX0; demux in ISR */

/* TMRX1.CR */
#define LD_TMRX1_CR (*(volatile uint32_t *)(LD_TMRX1_BASE + 0x00000000UL))


/* -------------------------------------------------------------------------- */
/* DMAX */

/* DMAX.CH (2 elements, 0x10 bytes apart) */
typedef struct {
    volatile uint32_t CTRL;           /* 0x00 */
    uint8_t           RESERVED0[12];  /* 0x04  (reserved) */
} ld_dmax_ch_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_ch_t, CTRL) == 0x00, LD_DMAX_CH_CTRL_offset, "DMAX.CH.CTRL offset");
REGFORGE_STATIC_ASSERT(sizeof(ld_dmax_ch_t) == 0x10, LD_DMAX_CH_SIZE, "DMAX.CH element size vs dimIncrement");

/* DMAX.EXTRA */
typedef struct {
    volatile uint32_t CTRL;  /* 0x00 */
} ld_dmax_extra_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_extra_t, CTRL) == 0x00, LD_DMAX_EXTRA_CTRL_offset, "DMAX.EXTRA.CTRL offset");

typedef struct {
    ld_dmax_ch_t    CH[2];  /* 0x00 */
    ld_dmax_extra_t EXTRA;  /* 0x20 */
} ld_dmax_t;
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_t, CH) == 0x00, LD_DMAX_CH_offset, "DMAX.CH offset");
REGFORGE_STATIC_ASSERT(offsetof(ld_dmax_t, EXTRA) == 0x20, LD_DMAX_EXTRA_offset, "DMAX.EXTRA offset");

/* DMAX @ 0x40057000 */
#define LD_DMAX_BASE (0x40057000UL)
REGFORGE_MAYBE_UNUSED static ld_dmax_t *const LD_DMAX = (ld_dmax_t *)LD_DMAX_BASE;

/* DMAX.CH[2].CTRL */
#define LD_DMAX_CH_CTRL(i) (*(volatile uint32_t *)(LD_DMAX_BASE + 0x00000000UL + (i) * 0x00000010UL))

/* DMAX.EXTRA.CTRL */
#define LD_DMAX_EXTRA_CTRL (*(volatile uint32_t *)(LD_DMAX_BASE + 0x00000020UL))

#endif /* REGFORGE_LINTDEMO_H */
