/*
 * DemoMCU register definitions.
 * Minimal demo device used by the regforge test suite
 *
 * Device:  DemoMCU (DemoCorp, series DemoSeries)
 * Version: 1.0
 *
 * Source license (copied from the SVD <licenseText>):
 *   Copyright (c) 2024 DemoCorp.
 *   Licensed under the Apache License, Version 2.0.
 *
 * The register definitions generated below carry no license restrictions
 * (CC0-1.0, public domain). Use them freely, including in proprietary
 * firmware, with no attribution or licensing obligation.
 *
 * Source:  minimal.svd
 * sha256:  3fc2931f16f8a488b1966ec09966764fe344b13e9551dea0c41eb2549bcb9ca4
 * Command: regforge tests/fixtures/svd/minimal.svd -o tests/golden/c/minimal.h
 * Generated by regforge 0.0.1 -- do not edit.
 */
#ifndef REGFORGE_DEMOMCU_H
#define REGFORGE_DEMOMCU_H

#include <stdint.h>
#include <limits.h>
#include <assert.h>

#define DEMOMCU_ADDRESS_UNIT_BITS 8
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
_Static_assert(CHAR_BIT == DEMOMCU_ADDRESS_UNIT_BITS,
    "regforge: this header targets 8-bit address units; "
    "the compiler's CHAR_BIT disagrees -- regenerate with a matching emitter mode.");
#else
/* Pre-C11 has no _Static_assert; a negative array size fails the build the
 * same way (without a message) when CHAR_BIT disagrees. */
typedef char DEMOMCU_assert_address_unit_bits[(CHAR_BIT == DEMOMCU_ADDRESS_UNIT_BITS) ? 1 : -1];
#endif

#define DEMOMCU_BUS_WIDTH 32
#define DEMOMCU_SVD_VERSION "1.0"
#define DEMOMCU_SVD_SHA256 "3fc2931f16f8a488b1966ec09966764fe344b13e9551dea0c41eb2549bcb9ca4"

/* CPU ---------------------------------------------------------------------- */
#define DEMOMCU_CPU_CORE "CM0PLUS"
#define DEMOMCU_CPU_REVISION "r0p1"
#define DEMOMCU_NVIC_PRIO_BITS 2
#define DEMOMCU_NUM_IRQS 32
#define DEMOMCU_HAS_FPU 0
#define DEMOMCU_HAS_MPU 1
#define DEMOMCU_HAS_VTOR 1

#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__)
#error "DemoMCU is little-endian, but the compiler targets a different byte order."
#endif

#if defined(__ARM_FP) && !DEMOMCU_HAS_FPU
#error "Building with FPU codegen for DemoMCU, which has no FPU (check -mfloat-abi / -mfpu)."
#endif

#define DEMOMCU_IRQ_PRIO_LEVELS (1U << DEMOMCU_NVIC_PRIO_BITS)

/* `inline` is C99; on C89 degrade to `static` -- plus GCC/Clang's unused
 * attribute so an unreferenced helper does not warn under -Wall. */
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#define DEMOMCU_INLINE static inline
#elif defined(__GNUC__)
#define DEMOMCU_INLINE static __attribute__((unused))
#else
#define DEMOMCU_INLINE static
#endif

/* Align an interrupt priority to this core's implemented bits. NVIC priority
 * registers are MSB-aligned, so the value is shifted into the top
 * 2 bit(s); priorities >= the level count truncate in hardware. */
DEMOMCU_INLINE uint8_t demomcu_irq_prio(uint8_t priority)
{
    assert(priority < DEMOMCU_IRQ_PRIO_LEVELS);
    return (uint8_t)(priority << (8U - DEMOMCU_NVIC_PRIO_BITS));
}

/* GPIOA - General purpose I/O port A */
#define GPIOA_BASE (0x40020000UL)

/* GPIOA.MODER - Mode register */
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0x00000000UL))
#define GPIOA_MODER_MODE0_Pos (0U)
#define GPIOA_MODER_MODE0_Msk (0x00000003UL)
#define GPIOA_MODER_MODE0_INPUT (0U)
#define GPIOA_MODER_MODE0_OUTPUT (1U)
#define GPIOA_MODER_MODE0_ALTERNATE (2U)
#define GPIOA_MODER_MODE0_ANALOG (3U)

/* GPIOA.ODR - Output data register */
#define GPIOA_ODR (*(volatile uint32_t *)(GPIOA_BASE + 0x00000014UL))
#define GPIOA_ODR_OD0_Pos (0U)
#define GPIOA_ODR_OD0_Msk (0x00000001UL)

#endif /* REGFORGE_DEMOMCU_H */
