/*
 * DemoMCU register definitions.
 * Minimal demo device used by the regforge test suite
 *
 * Device:  DemoMCU (DemoCorp, series DemoSeries)
 * Version: 1.0
 *
 * Source license (copied from the SVD <licenseText>):
 *   Copyright (c) 2024 DemoCorp.
 *   Licensed under the Apache License, Version 2.0.
 *
 * The register definitions generated below carry no license restrictions
 * (CC0-1.0, public domain). Use them freely, including in proprietary
 * firmware, with no attribution or licensing obligation.
 *
 * Source:  minimal.svd
 * sha256:  b52350f1de16baad7e0c3b03c8d7d7d817d8d2cbd6eba89b2aa6d8c3f8f74282
 * Command: regforge tests/fixtures/svd/minimal.svd -o tests/golden/c/minimal.h
 * Generated by regforge 0.0.1 -- do not edit.
 */
#ifndef REGFORGE_DEMOMCU_H
#define REGFORGE_DEMOMCU_H

#include <stdint.h>
#include <stddef.h>
#include <limits.h>
#include <assert.h>

#ifndef REGFORGE_COMPAT_H
#define REGFORGE_COMPAT_H

/* Language standard as a comparable number (0 if not a Standard C compiler). */
#if defined(__STDC_VERSION__)
#  define REGFORGE_STDC __STDC_VERSION__
#else
#  define REGFORGE_STDC 0L
#endif

/* REGFORGE_STATIC_ASSERT(cond, tag, msg) -- compile-time check.
 * C++11+ and C11/C23 have a language construct; older dialects fall back to a
 * negative-array typedef named REGFORGE_assert_<tag>. `tag` must be unique per
 * translation unit -- regforge passes a device-namespaced tag. */
#if defined(__cplusplus) && (__cplusplus >= 201103L)
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) static_assert(cond, msg)
#elif REGFORGE_STDC >= 201112L
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) _Static_assert(cond, msg)
#else
#  define REGFORGE_STATIC_ASSERT(cond, tag, msg) \
       typedef char REGFORGE_assert_##tag[(cond) ? 1 : -1]
#endif

/* REGFORGE_INLINE -- inline with internal linkage.
 * `inline` is C99/C++; on C89 degrade to `static`, plus the unused attribute
 * (on compilers that support it) so an unreferenced helper stays warning-free. */
#if defined(__cplusplus) || REGFORGE_STDC >= 199901L
#  define REGFORGE_INLINE static inline
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_INLINE static __attribute__((unused))
#else
#  define REGFORGE_INLINE static
#endif

/* REGFORGE_MAYBE_UNUSED -- suppress "defined but not used" on an entity a given
 * translation unit may legitimately not reference. Used as a *prefix* on the
 * declaration (required by [[maybe_unused]]; also valid for __attribute__). */
#if defined(__cplusplus) && (__cplusplus >= 201703L)
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]
#elif REGFORGE_STDC >= 202311L
#  define REGFORGE_MAYBE_UNUSED [[maybe_unused]]              /* C23 */
#elif defined(__GNUC__) || defined(__clang__) \
   || defined(__CC_ARM) || defined(__ICCARM__)
#  define REGFORGE_MAYBE_UNUSED __attribute__((unused))       /* GCC/Clang/armclang/armcc5/IAR8+ */
#else
#  define REGFORGE_MAYBE_UNUSED                                /* MSVC (no such warning) + exotic */
#endif

#endif /* REGFORGE_COMPAT_H */

#define DEMOMCU_ADDRESS_UNIT_BITS 8
REGFORGE_STATIC_ASSERT(CHAR_BIT == DEMOMCU_ADDRESS_UNIT_BITS, DEMOMCU_address_unit_bits,
    "regforge: this header targets 8-bit address units; "
    "the compiler's CHAR_BIT disagrees -- regenerate with a matching emitter mode.");

#define DEMOMCU_BUS_WIDTH 32
#define DEMOMCU_SVD_VERSION "1.0"
#define DEMOMCU_SVD_SHA256 "b52350f1de16baad7e0c3b03c8d7d7d817d8d2cbd6eba89b2aa6d8c3f8f74282"

/* CPU ---------------------------------------------------------------------- */
#define DEMOMCU_CPU_CORE "CM0PLUS"
#define DEMOMCU_CPU_REVISION "r0p1"
#define DEMOMCU_NVIC_PRIO_BITS 2
#define DEMOMCU_NUM_IRQS 32
#define DEMOMCU_HAS_FPU 0
#define DEMOMCU_HAS_MPU 1
#define DEMOMCU_HAS_VTOR 1

#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__)
#error "DemoMCU is little-endian, but the compiler targets a different byte order."
#endif

#if defined(__ARM_FP) && !DEMOMCU_HAS_FPU
#error "Building with FPU codegen for DemoMCU, which has no FPU (check -mfloat-abi / -mfpu)."
#endif

#define DEMOMCU_IRQ_PRIO_LEVELS (1U << DEMOMCU_NVIC_PRIO_BITS)

/* Align an interrupt priority to this core's implemented bits. NVIC priority
 * registers are MSB-aligned, so the value is shifted into the top
 * 2 bit(s); priorities >= the level count truncate in hardware. */
REGFORGE_INLINE uint8_t demomcu_irq_prio(uint8_t priority)
{
    assert(priority < DEMOMCU_IRQ_PRIO_LEVELS);
    return (uint8_t)(priority << (8U - DEMOMCU_NVIC_PRIO_BITS));
}

/* ========================================================================== */
/* GPIOA -- General purpose I/O port A */

typedef struct {
    volatile uint32_t       MODER;          /* 0x00  Mode register */
    uint8_t                 RESERVED0[12];  /* 0x04  (reserved) */
    volatile const uint32_t IDR;            /* 0x10  Input data register */
    volatile uint32_t       ODR;            /* 0x14  Output data register */
} dc_gpioa_t;
REGFORGE_STATIC_ASSERT(offsetof(dc_gpioa_t, MODER) == 0x00, DC_GPIOA_MODER_offset, "GPIOA.MODER offset");
REGFORGE_STATIC_ASSERT(offsetof(dc_gpioa_t, IDR) == 0x10, DC_GPIOA_IDR_offset, "GPIOA.IDR offset");
REGFORGE_STATIC_ASSERT(offsetof(dc_gpioa_t, ODR) == 0x14, DC_GPIOA_ODR_offset, "GPIOA.ODR offset");

/* GPIOA @ 0x40020000 */
#define DC_GPIOA_BASE (0x40020000UL)
REGFORGE_MAYBE_UNUSED static dc_gpioa_t *const DC_GPIOA = (dc_gpioa_t *)DC_GPIOA_BASE;

/* GPIOA.MODER - Mode register */
#define DC_GPIOA_MODER (*(volatile uint32_t *)(DC_GPIOA_BASE + 0x00000000UL))
#define DC_GPIOA_MODER_RESET_VALUE (0x00000000UL)
#define DC_GPIOA_MODER_MODE0_Pos (0U)
#define DC_GPIOA_MODER_MODE0_Msk (0x00000003UL)
#define DC_GPIOA_MODER_MODE0_INPUT (0U)
#define DC_GPIOA_MODER_MODE0_OUTPUT (1U)
#define DC_GPIOA_MODER_MODE0_ALTERNATE (2U)
#define DC_GPIOA_MODER_MODE0_ANALOG (3U)

/* GPIOA.IDR - Input data register */
#define DC_GPIOA_IDR (*(volatile const uint32_t *)(DC_GPIOA_BASE + 0x00000010UL))

/* GPIOA.ODR - Output data register */
#define DC_GPIOA_ODR (*(volatile uint32_t *)(DC_GPIOA_BASE + 0x00000014UL))
#define DC_GPIOA_ODR_RESET_VALUE (0x00000000UL)
#define DC_GPIOA_ODR_RESET_MASK (0x0000FFFFUL)
#define DC_GPIOA_ODR_OD0_Pos (0U)
#define DC_GPIOA_ODR_OD0_Msk (0x00000001UL)

/* ========================================================================== */
/* UART -- Universal async receiver/transmitter (family: UART0, UART1) */

typedef struct {
    volatile uint32_t       DR;  /* 0x00  Data register */
    volatile const uint32_t SR;  /* 0x04  Status register */
} dc_uart_t;
REGFORGE_STATIC_ASSERT(offsetof(dc_uart_t, DR) == 0x00, DC_UART_DR_offset, "UART.DR offset");
REGFORGE_STATIC_ASSERT(offsetof(dc_uart_t, SR) == 0x04, DC_UART_SR_offset, "UART.SR offset");

/* UART0 @ 0x40004000 */
#define DC_UART0_BASE (0x40004000UL)
REGFORGE_MAYBE_UNUSED static dc_uart_t *const DC_UART0 = (dc_uart_t *)DC_UART0_BASE;

/* UART0.DR - Data register */
#define DC_UART0_DR (*(volatile uint32_t *)(DC_UART0_BASE + 0x00000000UL))

/* UART0.SR - Status register */
#define DC_UART0_SR (*(volatile const uint32_t *)(DC_UART0_BASE + 0x00000004UL))

/* UART1 @ 0x40004400 */
#define DC_UART1_BASE (0x40004400UL)
REGFORGE_MAYBE_UNUSED static dc_uart_t *const DC_UART1 = (dc_uart_t *)DC_UART1_BASE;

/* UART1.DR - Data register */
#define DC_UART1_DR (*(volatile uint32_t *)(DC_UART1_BASE + 0x00000000UL))

/* UART1.SR - Status register */
#define DC_UART1_SR (*(volatile const uint32_t *)(DC_UART1_BASE + 0x00000004UL))

/* ========================================================================== */
/* SPI -- Serial peripheral interface (family: SPI0, SPI1) */

typedef struct {
    volatile uint32_t CR;  /* 0x00  Control register */
    volatile uint32_t DR;  /* 0x04  Data register */
} dc_spi_t;
REGFORGE_STATIC_ASSERT(offsetof(dc_spi_t, CR) == 0x00, DC_SPI_CR_offset, "SPI.CR offset");
REGFORGE_STATIC_ASSERT(offsetof(dc_spi_t, DR) == 0x04, DC_SPI_DR_offset, "SPI.DR offset");

/* SPI0 @ 0x40008000 */
#define DC_SPI0_BASE (0x40008000UL)
REGFORGE_MAYBE_UNUSED static dc_spi_t *const DC_SPI0 = (dc_spi_t *)DC_SPI0_BASE;

/* SPI0.CR - Control register */
#define DC_SPI0_CR (*(volatile uint32_t *)(DC_SPI0_BASE + 0x00000000UL))

/* SPI0.DR - Data register */
#define DC_SPI0_DR (*(volatile uint32_t *)(DC_SPI0_BASE + 0x00000004UL))

/* SPI1 @ 0x40008400 */
#define DC_SPI1_BASE (0x40008400UL)
REGFORGE_MAYBE_UNUSED static dc_spi_t *const DC_SPI1 = (dc_spi_t *)DC_SPI1_BASE;

/* SPI1.CR - Control register */
#define DC_SPI1_CR (*(volatile uint32_t *)(DC_SPI1_BASE + 0x00000000UL))

/* SPI1.DR - Data register */
#define DC_SPI1_DR (*(volatile uint32_t *)(DC_SPI1_BASE + 0x00000004UL))

/* ========================================================================== */
/* TIM -- Advanced timer */

typedef struct {
    volatile uint32_t CR1;  /* 0x00  Control register 1 */
    volatile uint32_t ARR;  /* 0x04  Auto-reload register */
} dc_tim_t;
REGFORGE_STATIC_ASSERT(offsetof(dc_tim_t, CR1) == 0x00, DC_TIM_CR1_offset, "TIM.CR1 offset");
REGFORGE_STATIC_ASSERT(offsetof(dc_tim_t, ARR) == 0x04, DC_TIM_ARR_offset, "TIM.ARR offset");

/* TIM1 @ 0x40010000 */
#define DC_TIM1_BASE (0x40010000UL)
REGFORGE_MAYBE_UNUSED static dc_tim_t *const DC_TIM1 = (dc_tim_t *)DC_TIM1_BASE;

/* TIM1.CR1 - Control register 1 */
#define DC_TIM1_CR1 (*(volatile uint32_t *)(DC_TIM1_BASE + 0x00000000UL))

/* TIM1.ARR - Auto-reload register */
#define DC_TIM1_ARR (*(volatile uint32_t *)(DC_TIM1_BASE + 0x00000004UL))

/* ========================================================================== */
/* TIM6 -- Basic timer */

typedef struct {
    volatile uint32_t CR1;  /* 0x00  Control register 1 */
} dc_tim6_t;
REGFORGE_STATIC_ASSERT(offsetof(dc_tim6_t, CR1) == 0x00, DC_TIM6_CR1_offset, "TIM6.CR1 offset");

/* TIM6 @ 0x40011000 */
#define DC_TIM6_BASE (0x40011000UL)
REGFORGE_MAYBE_UNUSED static dc_tim6_t *const DC_TIM6 = (dc_tim6_t *)DC_TIM6_BASE;

/* TIM6.CR1 - Control register 1 */
#define DC_TIM6_CR1 (*(volatile uint32_t *)(DC_TIM6_BASE + 0x00000000UL))

#endif /* REGFORGE_DEMOMCU_H */
